[project]
name = "rt-scheduling-simulator"
version = "0.0.0"
description = "Real-Time Scheduling Simulator built for my Bachelor's Thesis"
dependencies = [
    "flask",
]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"